### PR TITLE
fix: performing a data transfer for data offers retrieved through the catalog url in the catalog browser wont work

### LINKED ISSUE #75: Performing a Data-Transfer for Data-Offers retrieved through the Catalog URL in the Catalog Browser wont work
# Bug Report

## Description
Performing a data-transfer should not be possible for data-offers, which where retrieved using the Catalog URL in the Catalog Browser.

https://github.com/sovity/edc-ui/blob/845482ed21a94b2ebe2448786efaac75db58a801/src/modules/edc-demo/components/contract-viewer/contract-viewer.component.ts#L130

### Expected Behavior
- Retrieving the contractnegotiation using the contractId
- Using the contractnegotiations `counterPartyAddress` to find the other connectors address

### Observed Behavior
- The catalog is fetched
- Then the asset is used to retrieve the counterParty from the assets `originator` field

### PR DESCRIPTION
**Pull request by efiege**
# Pull Request
ContractAgreementTransferApi-Extension: Providing an endpoint to start a data-transfer for a contract-agreement

## How Has This Been Tested?
-   Local IntegrationTest

## Linked Issue(s)
-   fixes #75 

# Checklist

-   [x] I have **formatted the title** correctly and precisely
-   [x] My code follows the **style guidelines** of this project
-   [x] I have performed a **self-review** of my own code
-   [x] I have **commented** my code, particularly in hard-to-understand areas and public classes/methods
-   [x] I have made corresponding changes to the **documentation**
-   [x] My changes generate **no new warnings** (performed checkstyle check locally)
-   [x] I have added **tests that prove my fix** is effective or that my feature works
-   [x] New and existing unit **tests pass locally** with my changes
-   [x] Any dependent **changes have been merged** and published in downstream modules
-   [x] I have added/updated **copyright headers**

### CODE REVIEW

File: extensions/contract-agreement-transfer-api/src/main/java/de/sovity/edc/extension/contractagreementtransferapi/controller/TransferRequestDtoToDataRequestTransformer.java [hunk 1]
```diff
@@ -0,0 +1,99 @@
...
+                .protocol("ids-multipart")
+                .build();
+    }
+
+    private String removeDuplicatedPrefixIfPresent(String assetId) {
+        return assetId.startsWith("urn:artifact:urn:artifact:") ?
+                assetId.substring("urn:artifact:".length()) : assetId;
+    }
+
+    private ContractNegotiation getNegotiationForAgreementId(String contractAgreementId) {
```
Comment (richardtreier) [inline extensions/contract-agreement-transfer-api/src/main/java/de/sovity/edc/extension/contractagreementtransferapi/controller/TransferRequestDtoToDataRequestTransformer.java:90]: should have it's own unit, either ContractNegotiationUtils, ContractNegotiationFetcher or ContractNegotiationService2

File: extensions/contract-agreement-transfer-api/src/main/java/de/sovity/edc/extension/contractagreementtransferapi/controller/ContractAgreementTransferApiController.java [hunk 2]
```diff
@@ -0,0 +1,68 @@
...
+import org.eclipse.edc.api.transformer.DtoTransformerRegistry;
+import org.eclipse.edc.connector.spi.transferprocess.TransferProcessService;
+import org.eclipse.edc.connector.transfer.spi.types.DataRequest;
+import org.eclipse.edc.spi.monitor.Monitor;
+import org.eclipse.edc.web.spi.exception.InvalidRequestException;
+
+import java.time.Clock;
+
+@Produces({MediaType.APPLICATION_JSON})
+@Path("/transfer")
```
Comment (richardtreier) [inline extensions/contract-agreement-transfer-api/src/main/java/de/sovity/edc/extension/contractagreementtransferapi/controller/ContractAgreementTransferApiController.java:31]: API Endpoint should follow REST STandardshttps://restfulapi.net/resource-naming/

e.g. POST /contractagreements/{id}/transfer

File: extensions/contract-agreement-transfer-api/src/main/java/de/sovity/edc/extension/contractagreementtransferapi/controller/ContractAgreementTransferRequestDto.java [hunk 3]
```diff
@@ -0,0 +1,76 @@
...
+import com.fasterxml.jackson.annotation.JsonCreator;
+import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
+import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
+import jakarta.validation.constraints.NotNull;
+import org.eclipse.edc.spi.types.domain.DataAddress;
+
+@JsonDeserialize(builder = ContractAgreementTransferRequestDto.Builder.class)
+public class ContractAgreementTransferRequestDto {
+
+    private String id;
```
Comment (richardtreier) [inline extensions/contract-agreement-transfer-api/src/main/java/de/sovity/edc/extension/contractagreementtransferapi/controller/ContractAgreementTransferRequestDto.java:26]: will be contained in url?

File: extensions/contract-agreement-transfer-api/src/main/java/de/sovity/edc/extension/contractagreementtransferapi/controller/ContractAgreementTransferRequestDto.java [hunk 4]
```diff
@@ -0,0 +1,76 @@
...
+    @NotNull(message = "contractId cannot be null")
+    private String contractAgreementId;
```
Comment (richardtreier) [inline extensions/contract-agreement-transfer-api/src/main/java/de/sovity/edc/extension/contractagreementtransferapi/controller/ContractAgreementTransferRequestDto.java:28]: or rather, this belongs in the url

The API Model should only contain information that is relevant, and exactly the relevant information. Either we use only DataAddress or we create an object that contains the difference, as in, only the fields that won't be overwritten by us.

As in, violates single object responsibility.

**Review by richardtreier — CHANGES_REQUESTED** [review]
